### ISSUE TITLE
Remove the literal burger menu?

### ISSUE THREAD

**Issue by jmeas** [marionettejs/marionettejs.com#105]
It's good as a joke, but this is an actual website that people need to navigate. Sure, folks who are 'in' on the term 'burger menu' will get it, but it's a bit presumptuous to assume that everyone using our site will.

I'd rather our site be more navigable for more people than more funny for a few.

If we want to do fun stuff like this maybe we can hide it as an easter egg, but not make it the default behavior?

**Comment by paulfalgout** [comment]
:+1:

**Comment by samccone** [comment]
:hamburger:

**Comment by jdaudier** [comment]
i knew this wouldn't get passed by you. :cry: i figured that if anyone is on marionette's mobile site, then they're a developer and know what a hamburger icon is. thought it would add a little personality to the site.

with that being said, I will go change it to the boring 3 lines.

**Comment by samccone** [comment]
heh that is why I liked it @jdaudier :) 

people that go to marionettejs.com on their phones are typically a special kind of person....

**Comment by jdaudier** [comment]
is this something I can ask the community about in the marionette chat room?

**Comment by samccone** [comment]
heh I think it is prob the most "professional" to make it the 3 lines for now

**Comment by kkemple** [comment]
^ i agree most professional, but the hamburger is way funnier lol :hamburger:

**Comment by jdaudier** [comment]
ok 3 lines it is ... no problemo

![img](http://i.stack.imgur.com/KVkTq.jpg)
