### ISSUE TITLE
Remove "Requirements" section from home page?

### ISSUE THREAD

**Issue by jmeas** [marionettejs/marionettejs.com#106]
The requirements section can be removed, I think. That information really only needs to be on an installation page...not near the top of our landing page. To me, if Developer Jane comes to our website, the last thing I want her to think about is all of the things she needs on her page for `marionette.core.js` to work. I want her to focus on all of the problems it solves for you on top of Backbone. Once she has decided to install it is when she will need to know what the reqs are.

**Comment by jmeas** [comment]
@samccone brought up his thoughts on this section [over here](https://github.com/marionettejs/marionettejs.com/issues/79#issuecomment-68825138)!

**Comment by jdaudier** [comment]
Maybe the requirements section can be replaced with a "Why Marionette?" section with like a bulleted list of the top 3 to 5 reasons

**Comment by jmeas** [comment]
That's definitely an option we should consider. I'd like to see what people can come up with for those bulleted items. I'm worried that we won't be able to come up with anything that's as communicative as just showing some really kickass examples on the home page. I like how Ember organizes their page:

Feature A. This is what it does. This is why it kicks ass. Code example.
Feature B. 
...and so on.

If we make that our homepage, then the entire page is a really in-depth bulleted list, and we don't need to restrain ourselves to trying to summarize really complex ideas in a few words.

But maybe there's a place for both an abridged version and a more detailed one!

**Comment by kkemple** [comment]
I completely agree with @jmeas, we are on-boarding two new developers right now and when we said we use Marionette both of them asked where they could get good information on how to use it, I have to give them a curated list of blog posts and repos to look at, etc... but really they should be able to get that info just by landing on the homepage.

**Comment by kkemple** [comment]
We use the docs all the time when we want API specifics but as far as how all the parts fit together we have to send them elsewhere

**Comment by jmeas** [comment]
@kkemple, we also plan to have guides which will show very in-depth how all the pieces fit together (#98). My idea for a home page is a bit different from that. You wouldn't send your devs to the home page to learn how the pieces fit. That'd be what the guides are for. But you might send someone who, say, is accustomed to writing plain Backbone to show them how Marionette can clean up their code. It's conveying the same information as a bulleted list showing off our best features, but doing it in slightly more detail. Does that make sense?

**Comment by kkemple** [comment]
@jmeas yeah absolutely, when I said how to use it, I really meant what it is. More along the lines of what you were saying, the features of Marionette, why use it, where does it improve upon Backbone, etc. Not so much on application structure and implementation specifics, although I am looking forward to the guides as well!

Something like Ember's homepage. (As you said :smile:)

**Comment by jmeas** [comment]
dope :+1:

**Comment by peterblazejewicz** [comment]
I think `requirements` sounds just terrible. Reminds me Windows software stack, (first one from google search):
http://www.acmefiles.com/FAQ/windowsdefender/143-what-are-the-system-requirements-for-windows-defender
**Ember** has dependencies but does not print them in bold letters. It's enough to show people what to include in header scripts to get basic idea what's required (and let them use Bower or .zip)

**Comment by jdaudier** [comment]
"Dependencies" perhaps

**Comment by jmeas** [comment]
Ha, good point, @peterblazejewicz! There's no question in my mind that we should obliterate the word 'requirements' from the site altogether. @jdaudier's suggestion to use "Dependencies" is a good one, I think.

I still contend that these dependencies or requirements or whatever we decide to call them don't belong on the home page tho'

**Comment by jasonLaster** [comment]
Yup! Let's get another page in soon. I had a PR for a second page, it'll be great. We'll have to add some partials get another guy using the layout.

**Comment by samccone** [comment]
we killed it
