### ISSUE TITLE
Mojotech?

### ISSUE THREAD

**Issue by jmeas** [marionettejs/marionettejs.com#111]
The old website may have been "handcrafted and coded" by Mojotech, but it seems that for this new website Mojotech is one of many contributors. Maybe we should downplay the Mojotech bit at the bottom of the page? One idea would be to introduce a more 'standard' footer, and then have

> Built by Mojotech and the Marionette community.

w/o any logo as part of it. Thoughts?

**Comment by samccone** [comment]
yeah we can :x: it

**Comment by samccone** [comment]
lets just throw the MT logo back into the logo list
