### ISSUE TITLE
video slider need minor responsive touch

### ISSUE THREAD

**Issue by jdaudier** [marionettejs/marionettejs.com#116]
The text overlaps (ping @kkemple)

I wonder if there's a way to remove the black bars on the images. Not a big deal though. 

https://www.dropbox.com/s/4qbml1lsy7f5ju8/Screenshot_2015-01-09-14-27-35.png?dl=0

**Comment by kkemple** [comment]
I can look tonight at really clean it up

**Comment by jdaudier** [comment]
Awesome burger!

**Comment by jdaudier** [comment]
thanks @peterblazejewicz for fixing this!

**Comment by samccone** [comment]
:clap:
