### ISSUE TITLE
Scroll-to-top arrow not showing up on Firefox

### ISSUE THREAD

**Issue by jdaudier** [marionettejs/marionettejs.com#118]
**Firefox, you disappoint me...**
![bug](https://cloud.githubusercontent.com/assets/1666031/5689165/4efb4c3a-982e-11e4-9950-4921602c53d5.png)

----
**really Firefox?**
![bug](https://cloud.githubusercontent.com/assets/1666031/5689393/0c3f56f8-9832-11e4-8cbe-761adedc31c2.png)

----
**Works ok on Chrome & Safari**
![no bug](https://cloud.githubusercontent.com/assets/1666031/5689168/5ae778ac-982e-11e4-888e-d81ea40d13c1.png)

**Comment by paulfalgout** [comment]
fixed https://github.com/marionettejs/marionettejs.com/pull/119

**Comment by jdaudier** [comment]
thanks @paulfalgout !
