### ISSUE TITLE
Twitter Card meta tags seems to be invalid

### ISSUE THREAD

**Issue by peterblazejewicz** [marionettejs/marionettejs.com#125]
The Twitter Card meta seems to have invalid type - the `card` - it is not supposed to have user defined value. It should have one of supported values (here `summary`, `summary_large_image` or maybe `product` can be used):

https://cards-dev.twitter.com/validator

Because of this I think Twitter's meta do not validate - and  Twitter uses Facebook OpenGraph instead (the same issue is ongoing on TryGhost)

I could do a PR with  updated card outlined below:
```
meta(name='twitter:card', value='summary')
  meta(name='twitter:creator', value='@marionettejs')
  meta(name='twitter:description', value='Marionette simplifies your Backbone application code with robust views and architecture solutions.')
  meta(name='twitter:site', value='@marionettejs')
  meta(name='twitter:title', value='The Backbone Framework')
```
it will be rendered to:
```
<meta name="twitter:card" value="summary">
<meta name="twitter:creator" value="@marionettejs">
<meta name="twitter:description" value="Marionette simplifies your Backbone application code with robust views and architecture solutions.">
<meta name="twitter:site" value="@marionettejs">
<meta name="twitter:title" value="The Backbone Framework">
```

https://dev.twitter.com/cards/types/summary

It will pass Twitter validation and will be used on Twitter - so content of title/description can be discussed.
I can verify it locally:
![20150110153922](https://cloud.githubusercontent.com/assets/14539/5691936/e476dd0a-98de-11e4-9cd3-7535b40938a7.jpg)

Thanks!

**Comment by jdaudier** [comment]
I think these are all leftover legacy code from the old site using Middleman.  Feel free to adjust as you see fit @peterblazejewicz. Thank you!

**Comment by samccone** [comment]
@peterblazejewicz awesome research, would you like to PR the fix for this? (if not we can) 

Thanks again!

**Comment by peterblazejewicz** [comment]
@samccone 
Yes, PR within couple of hours.
Thanks!
