### ISSUE TITLE
Brandish the burger

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/marionettejs.com#126]
Im not a marketer like Joanne or a designer like Nick, but I'm confident the Mn brand can accomodate the mobile hamburger nav. I propose we brand the burger w/ some Mn love and add it to the website. Brandishing the burger offers a chance to delete and troll the Internet community. And we know what that can do for page views and sentiment, think reddit and HN. So let's put our heads together and think brandy + burger + puppets.

**Comment by jmeas** [comment]
If we want our website to be fun and approachable, I think we can do it in other ways. I *much* prefer the three line menu to the literal take on the burger menu.

With that said, if everyone else thinks that it's a good idea, then go for it.

**Comment by samccone** [comment]
heh closing
