### ISSUE TITLE
The brand disappears on small screens (xs sizes/mobiles)

### ISSUE THREAD

**Issue by peterblazejewicz** [marionettejs/marionettejs.com#135]
I'm not sure if that was intended but currently the brand is hidden on small screens:

https://github.com/marionettejs/marionettejs.com/blob/master/src/stylesheets/_header.scss#L211-L213

![20150111225541](https://cloud.githubusercontent.com/assets/14539/5697030/0db0ebf0-99e5-11e4-8e6a-8238089abeae.jpg)

Wouldn't it better to let the brand stay visible on different sizes? (below describes a quick patch to existing CSS):

![responsive](https://cloud.githubusercontent.com/assets/14539/5697034/2933a002-99e5-11e4-866e-1dc1c8e54eca.gif)

similar:
https://github.com/marionettejs/marionettejs.com/issues/126

**Comment by samccone** [comment]
So it drops on purpose right now just because of the amount of vertical space the logo takes up, I think have the image swap to just the works would be a good idea, but not the tall M.

thoughts?

**Comment by jdaudier** [comment]
I will add it back. I purposely left it off since the logo is close by but then I realized once they scroll, the logo is not so close anymore.
