### ISSUE TITLE
Generating docs.

### ISSUE THREAD

**Issue by trusktr** [marionettejs/marionettejs.com#136]
Hello, I'm curious to know, are the docs on the new awesome Marionette doc site auto-generated? If so, how? Thanks for the tips in advance!

**Comment by samccone** [comment]
hi @trusktr thanks for the compliment, the docs are indeed auto generated, @thejameskyle did some great work with grunt and https://github.com/gordonwritescode/gitty and https://github.com/chjj/marked
 
you can follow along with the nitty gritty implementation details here
https://github.com/marionettejs/marionettejs.com/blob/master/tasks/compile-docs.js#L265

**Comment by trusktr** [comment]
Very cool! Thanks a ton!

*/#!/*JoePea
