### ISSUE TITLE
Non-minified files sometimes getting minified

### ISSUE THREAD

**Issue by jdaudier** [marionettejs/marionettejs.com#139]
backbone.marionette.js - this is currently minified
backbone.marionette.min.js - this is currently NOT minified

![2015-01-14_1235](https://cloud.githubusercontent.com/assets/1666031/5743883/31c9eea4-9bea-11e4-9cf0-cb56b8d1f8fe.png)

**Comment by jasonLaster** [comment]
nice catch

**Comment by jdaudier** [comment]
if someone can tell me how to fix this, i can try

**Comment by peterblazejewicz** [comment]
@jdaudier 
The actual files are created by download/copy routine:
https://github.com/marionettejs/marionettejs.com/blob/master/tasks/compile-downloads.sh
This task can be run from repo as grunt task:
```bash
grunt compileDownloads
Running "compileDownloads" task
  adding: tmp/backbone.marionette/ (stored 0%)
  adding: tmp/backbone.marionette/backbone.babysitter.js (deflated 69%)
  adding: tmp/backbone.marionette/backbone.js (deflated 71%)
  adding: tmp/backbone.marionette/backbone.marionette.js (deflated 77%)
  adding: tmp/backbone.marionette/backbone.marionette.map (deflated 63%)
  adding: tmp/backbone.marionette/backbone.marionette.min.js (deflated 75%)
  adding: tmp/backbone.marionette/backbone.wreqr.js (deflated 74%)
  adding: tmp/backbone.marionette/core/ (stored 0%)
  adding: tmp/backbone.marionette/core/backbone.marionette.js (deflated 76%)
  adding: tmp/backbone.marionette/core/backbone.marionette.map (deflated 62%)
  adding: tmp/backbone.marionette/core/backbone.marionette.min.js (deflated 74%)
  adding: tmp/backbone.marionette/jquery.js (deflated 70%)
  adding: tmp/backbone.marionette/json2.js (deflated 69%)
  adding: tmp/backbone.marionette/underscore.js (deflated 73%)

Done, without errors
```
If the actual content is wrong, the download/copy routine is to be investigated.

Thanks!

**Comment by jdaudier** [comment]
this is miraculously working now

**Comment by paulfalgout** [comment]
Actually cloudflare is sometime minifying our non-minified versions

**Comment by paulfalgout** [comment]
@samccone @thejameskyle We need to exclude our downloadables.

https://support.cloudflare.com/hc/en-us/articles/200172316-How-do-I-exclude-a-specific-URL-from-CloudFlare-s-caching-
