### ISSUE TITLE
Twitter card requires whitelisting (some *paper work*)

### ISSUE THREAD

**Issue by peterblazejewicz** [marionettejs/marionettejs.com#144]
Hi,

I've just tried to validate Twitter card:
https://cards-dev.twitter.com/validator
and some of you guys will have to submit @marionettejs card for whitelisting:
```
As a website owner you must opt-in to have cards displayed for your domain, and Twitter must approve the integration. To register your domain, please provide the following information:
[....]
```
*edited*: forgot to mention: just log to Twitter validator and when requesting validation for an url information should be shown.

That's common and they discuss topic on devs forum:
https://twittercommunity.com/t/cards-validator-says-approved-but-also-warn-not-whitelisted/23894/16

Preview of card:
![20150116225720](https://cloud.githubusercontent.com/assets/14539/5785141/7f731474-9dd3-11e4-9f30-018790c17c35.jpg)

It's just a `paper work` and should be no brainer:
![20150116225011](https://cloud.githubusercontent.com/assets/14539/5785146/9a8dc8b2-9dd3-11e4-95af-c3ce65087716.jpg)

Thanks!

**Comment by samccone** [comment]
filled it out!

**Comment by peterblazejewicz** [comment]
@samccone 
I think it needs to be redone. But after this PR is merged:

https://github.com/peterblazejewicz/marionettejs.com/commit/8546bae4f1031282be1e855934fe9c64f2e247c3

**Comment by samccone** [comment]
hmm poo ok will do

**Comment by samccone** [comment]
odd @peterblazejewicz 

I reapplied after a fresh deploy and looks like we are still having issues 

![screen shot 2015-02-04 at 11 15 51 pm](https://cloud.githubusercontent.com/assets/883126/6054976/d544f846-acc3-11e4-95f9-66ec67dc9969.png)
![screen shot 2015-02-04 at 11 15 13 pm](https://cloud.githubusercontent.com/assets/883126/6054975/d5407546-acc3-11e4-84d9-7013b267cb51.png)

**Comment by peterblazejewicz** [comment]
@samccone if still not approved can you wait a 24h - they could have a cached version (or anything).
If not I could append a post to this thread:
https://twittercommunity.com/t/warn-not-whitelisted-whitelist-request-was-approved-18-days-ago/25756
which people are using to fix problems with valid cards and whitelisting recently.
LGTY?

**Comment by samccone** [comment]
yeah ill redo it tonight

**Comment by peterblazejewicz** [comment]
subitted to Twitter devs:
https://twittercommunity.com/t/warn-not-whitelisted-whitelist-request-was-approved-18-days-ago/25756/51?u=blazejewicz

**Comment by samccone** [comment]
:+1: @peterblazejewicz

**Comment by peterblazejewicz** [comment]
update: moved to new thread at Twitter dev request:
https://twittercommunity.com/t/warn-not-whitelisted-whitelisting-problem/32261

**Comment by peterblazejewicz** [comment]
x-ref: #254

**Comment by peterblazejewicz** [comment]
x-ref: #255

**Comment by peterblazejewicz** [comment]
All fixed according to Twitter's developer input via #254 and #255:
https://twittercommunity.com/t/warn-not-whitelisted-whitelisting-problem/32261

cc: @samccone Can you resubmit again?

**Comment by samccone** [comment]
![screen shot 2015-02-16 at 5 41 45 pm](https://cloud.githubusercontent.com/assets/883126/6220334/256d820a-b603-11e4-8fc5-97e50d4f3ca4.png)
