### ISSUE TITLE
Add `defer` attribute to landing page script

### ISSUE THREAD

**Issue by peterblazejewicz** [marionettejs/marionettejs.com#151]
The lonely relevant page script tag can be loaded via defer in supported browser I believe:
```diff
diff --git a/src/layouts/layout.jade b/src/layouts/layout.jade
index 14cf2b1..81e0bcf 100644
--- a/src/layouts/layout.jade
+++ b/src/layouts/layout.jade
@@ -35,7 +35,7 @@ html(lang='en')
       include ../images/svg-sprite.svg
     block content
 
-    script(src="js/build.js?t=#{Date.now()}")
+    script(src="js/build.js?t=#{Date.now()}" defer)
     script.
       // Flattr
       (function() {
(END) 
```
At the moment all code is loaded via this script. See relevant:
https://github.com/marionettejs/marionettejs.com/issues/117
It could speed up rendering speed a little. `defer` nicely fall back in non supporting browsers (does nothing). The docs page layout has different script solution.

**Comment by samccone** [comment]
:+1: to this

**Comment by jmeas** [comment]
:+1:
