### ISSUE TITLE
Refactor links in `support` section for UX consistency

### ISSUE THREAD

**Issue by peterblazejewicz** [marionettejs/marionettejs.com#152]
Let me explain: 
links in support section of landing page do have icons - but icons are not clickable/interactive:

![20150117231838](https://cloud.githubusercontent.com/assets/14539/5790571/4e4d8038-9e9f-11e4-9a7b-fb4c1fd52761.jpg)

On the same page the same icons are clickable/interactive in main navigation:
![20150117232007](https://cloud.githubusercontent.com/assets/14539/5790575/7e5406ee-9e9f-11e4-86de-3962f6e1c0b5.jpg)

On documentation page icons are clickable:
![20150117232036](https://cloud.githubusercontent.com/assets/14539/5790576/88270310-9e9f-11e4-898b-0150718292ff.jpg)

So on contact section the same icons just sit in the background as design element - not as an interactive element already exposed to users.

Let me know if you want PR - but I think that @jdaudier could be interested

Thanks!

**Comment by jdaudier** [comment]
@peterblazejewicz it's all yours if you want it! 

So you're thinking of making the icons under Support interactive, correct?  If so, that works for me.

**Comment by peterblazejewicz** [comment]
@jdaudier Yes, exactly - just to be consistent with other solution and people habits.

**Comment by jdaudier** [comment]
Cool!  All yours @peterblazejewicz
