### ISSUE TITLE
Use the same navigation pattern for contact links [AI/UX]

### ISSUE THREAD

**Issue by peterblazejewicz** [marionettejs/marionettejs.com#153]
People tends to learn, automate interaction, order things - including navigation. Let's decide on order how they should contact Marionette, for example like this:
```
- [ ] gitter
- [ ] twitter
- [ ] github
```
![20150117232036](https://cloud.githubusercontent.com/assets/14539/5790595/a88bbc30-9ea0-11e4-9dde-a324d460d6b6.jpg)
![20150117232007](https://cloud.githubusercontent.com/assets/14539/5790596/a8946970-9ea0-11e4-95de-3b9ea01e6cf3.jpg)
![20150117231838](https://cloud.githubusercontent.com/assets/14539/5790597/a898dbd6-9ea0-11e4-9c7a-e68c6f61b7d3.jpg)

(the gitter is missing from one image - will be another issue).

Thanks!

**Comment by jdaudier** [comment]
Oh, the Gitter one is actually the "Support" link on the header.

**Comment by peterblazejewicz** [comment]
Yes, I know - I'm writing other ticket for this
