### ISSUE TITLE
VERSION tag is not the latest

### ISSUE THREAD

**Issue by jdaudier** [marionettejs/marionettejs.com#157]
How do we get the latest version number to show up on the site?

![tag1](https://cloud.githubusercontent.com/assets/1666031/5790849/70712dc8-9e7b-11e4-8ffe-728d2e1dd80c.png)

Seems like maybe something is broken here?

![2015-01-17_1901](https://cloud.githubusercontent.com/assets/1666031/5790854/b10558f0-9e7b-11e4-9639-6281eeebd8bd.png)

![tag](https://cloud.githubusercontent.com/assets/1666031/5790850/74276630-9e7b-11e4-9c3e-939ca4c6ba15.png)

**Comment by samccone** [comment]
Yeah you will want to update your submodule and it should just work :)

**Comment by jdaudier** [comment]
So I just need to add this change to my commit and push? Then when someone deploys, the site will be updated?  I wanna try to deploy when someone is available to back me up in case it breaks like last time.

![img](http://content.screencast.com/users/Joanne_Daudier/folders/Jing/media/6ae36095-dbb6-4346-b7fb-5ddcc684e406/00001170.png)
