### ISSUE TITLE
404 for jQuery source map

### ISSUE THREAD

**Issue by jdaudier** [marionettejs/marionettejs.com#162]
I see these 2 errors in the console.  Any idea why?

![2015-01-19_0029](https://cloud.githubusercontent.com/assets/1666031/5796252/638d03a0-9f72-11e4-9213-5b8558e2d390.png)

**Comment by peterblazejewicz** [comment]
We are including jQuery in minimized format which contains inline reference to source map file for supporting browser. So chrome tries to load that source map when dev consoles is open. 
To correct this we can either:
- use non-minified version of jQuery in build or:
- just copy jQuery .map file 
The second solution will just suppress chrome dev tools error. 
More correct is the first one, but then we should add minify steps to our build

**Comment by jdaudier** [comment]
How about the error in line 4 of build.js?  Any idea about that one?  Something to do with CORS it seems.

![2015-01-19_0029](https://cloud.githubusercontent.com/assets/1666031/5796387/2a987662-9f75-11e4-96fa-d095c7205910.png)

**Comment by peterblazejewicz** [comment]
One of included script (3rd party I believe) tries to set header for Ajax request(s). As it can be recreated locally it should be easy to spot which one

**Comment by peterblazejewicz** [comment]
x-ref: https://github.com/marionettejs/marionettejs.com/issues/164

**Comment by peterblazejewicz** [comment]
closed via #290
