### ISSUE TITLE
Copy jquery.min.map to dist as temp fix for #162

### ISSUE THREAD

**Issue by peterblazejewicz** [marionettejs/marionettejs.com#165]
May we do following change to remove warning from at least Chrome dev tools about source.map?
See:
https://github.com/marionettejs/marionettejs.com/issues/162

```diff
diff --git a/gruntfile.js b/gruntfile.js
index 4189736..6c72ee4 100644
--- a/gruntfile.js
+++ b/gruntfile.js
@@ -28,7 +28,7 @@ module.exports = function(grunt) {
 
     concat: {
       options: {
-        separator: ';\n'
+        separator: '\n'
       },
       dist: {
         src: [
@@ -89,6 +89,12 @@ module.exports = function(grunt) {
             expand: true,
             src: ['js/docs.js'],
             dest: 'dist'
+          },
+          {
+            expand: true,
+            cwd: 'bower_components/jquery/dist/',
+            src: ['jquery.min.map'],
+            dest: 'dist/js/'
           }
         ]
       }
```
At the current version the jQuery is copied as is and as minified version. We do not minify files - so jQuery comes with its own declaration for source map:
```JavaScript
//# sourceMappingURL=jquery.min.map
```
Browsers keep trying to load this file which is missing in `dist`.
Adding `jquery.min.map` to dist is not enough though - as we concatenate files using `;\n` separator - this is correct - but unfortunately should not be used for already minimized files (the rule is to not use minimized files in build process):
```JavaScript
//# sourceMappingURL=jquery.min.map;
```
Now browser try to fetch:
```
....jquery.min.map;
```
which is wrong url (semicolon is treated as part of url).

So to fully fix this the separator needs to be changed.

Is it worth to fix this? This change will assume that all files that are used in build are correctly written (semicolons are optional, no jshint to lint code at repo).

**Comment by samccone** [comment]
yes yes yes!

@peterblazejewicz you want to PR this or want me to?

----

I trust you enough to just open the PR's :D
