### ISSUE TITLE
Create an Inspector Promo page

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/marionettejs.com#168]
We should create a promo page, promo section, and link in the header for the inspector.

There's tons of content in the inspector README to base the copy off of. Also, all of you guys have used the Inspector so are qualified to describe it's benefits / features / super powers.

https://github.com/marionettejs/marionette.inspector

**Comment by samccone** [comment]
:+1: to this

**Comment by kkemple** [comment]
:+1:

**Comment by jasonLaster** [comment]
http://media.giphy.com/media/f2fX7GtXh1nbi/giphy.gif

Forgot to mention, the inspector also has a snazzy logo which we can use

**Comment by jdaudier** [comment]
a page page or something like this (modal) for the Inspector? http://codyhouse.co/demo/morphing-modal-window/index.html#0

**Comment by peterblazejewicz** [comment]
ng-inspector used to have clean, descriptive promo page:
http://ng-inspector.org/

**Comment by samccone** [comment]
oh wow that looks realllllllly nice @peterblazejewicz 

ping ping ping @lupinskij

**Comment by jasonLaster** [comment]
Nice

**Comment by samccone** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/883126/6116944/bdaee34a-b07e-11e4-9821-5e1c4af55322.jpg)


@lupinskij for the gold

**Comment by samccone** [comment]
This should prob should be a html5 video for that extra wow

**Comment by thejameskyle** [comment]
> should be a html5 video

I was thinking silverlight video actually

**Comment by samccone** [comment]
<object> prob

**Comment by jdaudier** [comment]
fresh!  so there'll be a link to this page from the homepage I assume?

**Comment by peterblazejewicz** [comment]
I think that Inspector should get prominent location - even replacing an item in navbar menu
@jdaudier heat maps can be helpful here (and any other analytics)

**Comment by samccone** [comment]
I'm excited for the map because then we can finally start removing features with some degree of confidence
