### ISSUE TITLE
Add a link to the inspector high on the page

### ISSUE THREAD

**Issue by cmaher** [marionettejs/marionettejs.com#178]
Right now, the only link is below Jason's talk, way down. I'm not sure where exactly the link should go, but I think it's important enough to be up high (maybe it should have its own section?)

**Comment by samccone** [comment]
:+1:

**Comment by peterblazejewicz** [comment]
What about refactoring docs/downloads into something like docs/downloads/tools (inspector)?:
Just a web page live edit:

![20150130215208](https://cloud.githubusercontent.com/assets/14539/5983103/5e46122c-a8ca-11e4-864c-c3e7f6b824dd.jpg)

The `Inspector` is obviously a link to relevant project (maybe project website in future) and section should have adequate copy about inspector + link to installation.
