### ISSUE TITLE
childEvents not supported in behavior.. other options? Is this an oversight? Am I dumb?

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/marionettejs.com#179]
My goal is for a behavior attached to a CollectionView to be able to know which ChildView was just interacted with by the user. It does not appear that this is currently possible.

Here's an example: http://codepen.io/Meo/pen/XJaGxo

And here's the code I'm trying:

	var CollectionViewBehavior = Marionette.Behavior.extend({
	  //  Does NOT run:
	  childEvents: {
		'do:stuff': function(args){
		  console.log('Model to do stuff on:', args.model);
		}
	  }
	});

	var ChildViewBehavior = Marionette.Behavior.extend({
	  triggers: {
		'click': 'do:stuff'
	  }
	});

	var MyChildView = Marionette.ItemView.extend({
	  template: _.template('MyChildView - click me!'),
	  behaviors: {
		ChildViewBehavior: {
		  behaviorClass: ChildViewBehavior
		}
	  }
	});

	var MyCollectionView = Marionette.CollectionView.extend({
		childView: MyChildView,
		behaviors: {
		  CollectionViewBehavior: {
			behaviorClass: CollectionViewBehavior
		  }
		},
		//  Does run:
		childEvents: {
		  'do:stuff': function(args){
			console.log('This totally works, but is not in a behavior to do stuff on:', args.model);
		  }
		}
	});

	var myCollectionView = new MyCollectionView({ collection: (new Backbone.Collection([{}]))});
	$('body').append(myCollectionView.render().el);
	  
Am I missing something? I get that Behaviors should be generic, so I think it makes sense that they don't support childEvents, but it leaves me thinking I have to do one of a few hacky workarounds to make this work.

Thoughts?

**Comment by samccone** [comment]
mind reopeneing on backbone.marionette repo plz

**Comment by MeoMix** [comment]
Oh. I need more coffee. Sorry.
