### ISSUE TITLE
Add a task to auto update submodule

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#186]
this is an annoying part of the release cycle, it should be pretty simple to make sure we have the latest via grunt command

**Comment by peterblazejewicz** [comment]
for the records: jQuery has been using Grunt for submodules with this:
https://github.com/jquery/jquery/commit/d01253e20158f53c08aa6bc0c1cf66806cd19148
https://github.com/jaubourg/grunt-update-submodules
This was before they switched to use Bower based dependencies during build:
https://github.com/jquery/jquery/pull/1358

**Comment by samccone** [comment]
yep this is taken care of since we do an auto deploy now :)

:shipit: :anchor:
