### ISSUE TITLE
Look at integrating russian translation work

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#195]
https://github.com/instanceofpro/marionettejs.ru/issues/34
http://instanceof.pro/marionettejs.ru/

@instanceofpro has been killing it and I want to find a way to integrate his work!

**Comment by instanceofpro** [comment]
how can i integrate my translation?

**Comment by samccone** [comment]
hi @instanceofpro great question, I would love to figure out a good solution. I have a feeling that we have some people in the community that have some strong opinions on the best way to do this. I will reach out and see.

**Comment by peterblazejewicz** [comment]
I've been using (and writing client side/server side code) for:
https://www.transifex.com
which has free plan for open source (no limits).
The @TryGhost team is using other service - which also has open source plans:
https://crowdin.com/page/in-action
They could look like to big guns for a project, but let's check them. 

Crowdsourced projects I've been translating with different solutions for string replacement: server or client side:
https://github.com/nodeschool/nodeschool.github.io
https://github.com/confcodeofconduct/confcodeofconduct.com

**Comment by samccone** [comment]
hey @instanceofpro @peterblazejewicz closing and moving to
#209

**Comment by peterblazejewicz** [comment]
:+1:
