### ISSUE TITLE
Add Hotjar for heatmap?

### ISSUE THREAD

**Issue by jdaudier** [marionettejs/marionettejs.com#196]
I got us a free lifetime account for [Hotjar](http://www.hotjar.com). Are you ok with me adding this to the site to see if it's helpful or not?  If not, we can always remove it later. Thoughts?

![2015-02-05_1953](https://cloud.githubusercontent.com/assets/1666031/6074336/e97df2c4-ad70-11e4-8e4f-d13cbb659e96.png)

**Comment by peterblazejewicz** [comment]
:+1: 
I'd only check if they require adding their script in the header. We put everything on the bottom and asynchronously.

**Comment by jdaudier** [comment]
Yes, the script is added into the `<head>` tag of every page we want to track.

http://inside.hotjar.com/support/solutions/articles/1000126936

Even though the Hotjar tracking code needs to be included at the top, the script itself will still load asynchronously. They use the same code loading technique that Google Analytics uses to ensure that site speed is not affected.

**Comment by peterblazejewicz** [comment]
That does not matter - we should keep in mind that their code will block rendering if loaded before entire page is loaded and parsed fully:
http://www.growingwiththeweb.com/2014/02/async-vs-defer-attributes.html
This is why we use `defer`. Let's keep this in mind. Otherwise they could be helpful

**Comment by peterblazejewicz** [comment]
@jdaudier It can be useful - we have different UI user experience on different screens - some content is deliberately hidden and not accessible - so that could be interesting to see how people interact with content/web site.

**Comment by peterblazejewicz** [comment]
@jdaudier Hotjar impact on web site speed is neglectable:
http://tools.pingdom.com/fpt/#!/JWACZ/http://marionettejs.com/
