### ISSUE TITLE
Broken links in companies (404)

### ISSUE THREAD

**Issue by peterblazejewicz** [marionettejs/marionettejs.com#204]
Can we contact and verify these links? (I've verified manually too as broken):
https://www.shopetti.com/
https://github.com/marionettejs/marionettejs.com/blob/master/src/sections/_companies.jade#L171

https://www.onehealth.com/
https://github.com/marionettejs/marionettejs.com/blob/master/src/sections/_companies.jade#L132

**Comment by samccone** [comment]
yep lets just delete them I suppose
