### ISSUE TITLE
Internationalization Work

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#209]
It is finally time that we start the effort to start translating documentation and site content for Marionettejs.com

If you are interested in supporting the cause leave your email  and language below and I will invite you to the tool that we are using!

Or sign up here
https://www.transifex.com/organization/marionettejs

-----

We are using a tool from www.transifex.com

![screen shot 2015-02-10 at 10 53 14 am](https://cloud.githubusercontent.com/assets/883126/6130435/24f7ef4e-b113-11e4-8826-94357dc83438.png)

**Comment by XescuGC** [comment]
Hi!, I'm from Barcelona (Spain) so I can help with the translations on Spanish and Catalan. I've never used a tool but this one (transifex) looks good.

**Comment by eduardojmatos** [comment]
Hi @samccone , I shall be happy to help translate to portuguese (eduardoj.matos@gmail.com).

**Comment by samccone** [comment]
@eduardojmatos :white_check_mark: 
@XescuGC can you leave your email and I will add you to the spanish team?

**Comment by JSteunou** [comment]
Totally up for french translation!

**Comment by samccone** [comment]
@JSteunou can you leave your email I will add you

**Comment by ingro** [comment]
Hello, I can help with italian If you need! :) (ingro85@gmail.com)

**Comment by samccone** [comment]
:white_check_mark: @ingro

**Comment by XescuGC** [comment]
my email is (xescugil@gmail.com)

**Comment by samccone** [comment]
@XescuGC :white_check_mark:  thanks!

**Comment by JSteunou** [comment]
@samccone find my way into transifex

**Comment by Spy-Seth** [comment]
It seems you haven't upload any phrases or word for now. It's normal ?

**Comment by samccone** [comment]
ah it does look incorrect @Spy-Seth investing how to get those in...

**Comment by Poplava** [comment]
I can help with Ukrainian or Russian! igor.poplava@gmail.com

**Comment by samccone** [comment]
kk @Spy-Seth all good to go now :white_check_mark:

**Comment by samccone** [comment]
@Poplava added to Russian and Ukrainian :white_check_mark:

**Comment by instanceofpro** [comment]
+1 for RU :)

**Comment by samccone** [comment]
:white_check_mark: @instanceofpro

**Comment by Spy-Seth** [comment]
So we have the site and the docs on one big file ? :scream: 

It's possible to split it a little more ? Separate the website, the documentations and the annotated source for example.

**Comment by samccone** [comment]
@Spy-Seth from my research the embed code from  www.transifex.com is smart and will do a per page + per locale request when looking up the strings to replace. Thus not really 1 large file :+1:

**Comment by instanceofpro** [comment]
@samccone What about different versions (1.x.x, 2.x.x, 3.x.x)?

**Comment by samccone** [comment]
yeah @instanceofpro I can add the latest 1.x.x docs ... will do now

**Comment by instanceofpro** [comment]
@samccone does www.transifex.com provide a version control for translations?

**Comment by samccone** [comment]
:white_check_mark: 1.8.8. docs added

**Comment by samccone** [comment]
@instanceofpro what do you mean by version control?

**Comment by instanceofpro** [comment]
@samccone we translate docs corresponds to v2.3.2 (current version). 
how will we translate when the v3.0.0 will be released?

**Comment by samccone** [comment]
Ah I see what you are saying @instanceofpro 

So the way that this tool works is that it looks at blocks of text and sees if they have changed, so in v3 some new text will need to be translated but most of it will carry over from the work that we have done before.  

The translations are not per page, rather per block of text. It is really quite awesome!

**Comment by peterblazejewicz** [comment]
@samccone I'll add my Transifex account and will help with Polish (pl_Pl). For some reason my Transifex account is blocked (i've already sent them support ticket) - once reset I'll simply join project.
Thanks!

**Comment by samccone** [comment]
awesome!

:white_check_mark: `pl_PL`

**Comment by vladmd** [comment]
I can help with Romanian

**Comment by samccone** [comment]
@vladmd what is your Email ... I will invite you

**Comment by samccone** [comment]
:white_check_mark: @vladmd 
thanks!

**Comment by samccone** [comment]
@vladmd come join us in chat https://gitter.im/marionettejs/marionettejs.com?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by samccone** [comment]
:+1: ok this is well underway and enabled on our site now

thanks everyone for the amazing work and let me know if there is anything else I can do!

**Comment by peterblazejewicz** [comment]
It even should work with iOS reader:
![20150215210805](https://cloud.githubusercontent.com/assets/14539/6204759/d4e20f7e-b556-11e4-977d-bdcd933ad4d2.jpg)

**Comment by samccone** [comment]
:clap: :clap: :clap: :clap: :clap:

**Comment by Spy-Seth** [comment]
:heart_eyes:
