### ISSUE TITLE
Long String Translation breaks several elements on the page

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#215]
For instance

- [x] `View Docs` in Russian is
`Посмотреть документацию`

and in French it is
- [x] `Voir la documentation`

We need to tweak the styles to handle this

**Comment by peterblazejewicz** [comment]
Translations always break web pages. Let's log it here

**Comment by JSteunou** [comment]
We can translate "View Docs" by just "Docs" or "Documentation", will be shorter. But it's a one shot solution.

**Comment by peterblazejewicz** [comment]
@JSteunou we will iterate design details keeping in mind different lengths now (I've just added clipping, overflowing or hinted min width for links/buttons we will expand in future iteration)

**Comment by samccone** [comment]
yeah @JSteunou Docs or Documentation is a fine translation that is what @instanceofpro ended up doing for Russian
