### ISSUE TITLE
Log section to hide or change from Transifex Live translation here

### ISSUE THREAD

**Issue by peterblazejewicz** [marionettejs/marionettejs.com#216]
Hi,

As reported on Gitter:
> For the translation process, we need to find away to manage the "5860 stargazers" string. Transiflex ask us to re-translate it each time the number of stars change.

Please log into this thread any part of Marionette web page you find should be excluded from automatic translation process.

We could instruct Transifex automated process which parts to avoid, exclude or use special `data-` attributes to provide custom English base word:
http://docs.transifex.com/developer/live/webmasters

- [x] stargazers (updated dynamically at runtime) triggers changed translation notification (I'll make sample correction and PR)

**Comment by samccone** [comment]
fixed!

**Comment by peterblazejewicz** [comment]
Thanks!
