### ISSUE TITLE
Missing strin in transiflex

### ISSUE THREAD

**Issue by Spy-Seth** [marionettejs/marionettejs.com#220]
The `more` and `less` string in `Companies Using Marionette` section are missing on Transiflex.

![screenshot](http://cl.ly/image/1m3S0q422m3x/Image%202015-02-12%20at%2010.44.15%20AM.png)
![screenshot](http://cl.ly/image/06272u332s3c/Image%202015-02-12%20at%2010.44.22%20AM.png)

**Comment by samccone** [comment]
I added the missing less and more

thanks for the catch @Spy-Seth !!!!
