### ISSUE TITLE
Shorten page titles + missing favicon on doc pages

### ISSUE THREAD

**Issue by mindrones** [marionettejs/marionettejs.com#224]
If you open many tabs of the documentation it's difficult to find the one you're looking for, because tabs tend to shrink and you can't see the most interesting part of the title:
• title is: `marionette.application - Marionette.js Docs`
• I just see: `marionette.a` or less

Also, the only page showing the Marionette logo as favicon is http://marionettejs.com/

It would be nice to have like:
- [Application](http://marionettejs.com/docs/v2.3.2/marionette.application.html) page title: `Application`
- [Region](http://marionettejs.com/docs/v2.3.2/marionette.region.html) page title: `Region`
- and so on...

If the favicon gets fixed there's probably no need to specify a `Marionette.js Docs` in the title.

**Comment by samccone** [comment]
hi @mindrones thanks for the awesome issue,

are you interested in opening a PR, would love to get you into the fold.
Hop into gitter and we can chat https://gitter.im/marionettejs/marionettejs.com?utm_source=share-link&utm_medium=link&utm_campaign=share-link


Anyway thanks so much!

**Comment by peterblazejewicz** [comment]
These actually are bugs I think:
- [ ] title of page is supposed to be generated as expected I think:
https://github.com/marionettejs/marionettejs.com/blob/master/tasks/compile-docs.js#L93-L104
- [ ] the icon is there but not linked
I'll fix the second now, so we could re-title issue and investigate title generation (`title` is within `yaml` file - ready to be used later).
