### ISSUE TITLE
Inline SVG logo/text in above the fold section #perfmatters

### ISSUE THREAD

**Issue by peterblazejewicz** [marionettejs/marionettejs.com#234]
Let's try to improve page speed rendering by minimizing number of request of above the fold content:
- [x] inline brand image svg via data:image conversion
- [x] inline brand text svg via data:image conversion

This is supposed to optimize rendering speed by minimizing number of requests required to render ATF content (as per Google screenshot):
![20150214014614](https://cloud.githubusercontent.com/assets/14539/6197753/bf3b992c-b3eb-11e4-832e-733d43d2aecd.jpg)

**Comment by samccone** [comment]
@peterblazejewicz Literally God mode

**Comment by jmeas** [comment]
this might be unresolved. I expect there's more to #235 than inlining a few imgs
