### ISSUE TITLE
minor style tweaks to new landing page

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#24]
certain things look very broken, if someone want to just go over the page and tweak it so it does not look broken that would be awesome.

**Comment by peterblazejewicz** [comment]
Can we close this? The page is under constant re-development as of time of writing.

**Comment by samccone** [comment]
I agree

**Comment by trezy** [comment]
Absolutely, I haven't touched the refactor since it became a rebasing nightmare.
