### ISSUE TITLE
Improve Marionette Inspector Chrome icon

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#253]
on http://marionettejs.com/inspector page the chrome icon looks jacked, we should fix this.. either get an svg or get a better png for the chrome icon.

**Comment by peterblazejewicz** [comment]
Super official rules are here:
https://developer.chrome.com/webstore/branding?csw=1

Their current logo is available here:
http://en.wikipedia.org/wiki/Google_Chrome
verified with official brand logos:
http://www.google.com/press/images.html
So we have to just desaturate SVG I think.

**Comment by peterblazejewicz** [comment]
@samccone does #260 closes this? Or should it stay open? thanks!

**Comment by samccone** [comment]
we are good to go now
