### ISSUE TITLE
Fix path to image used in OpenGraph/TwitterCads

### ISSUE THREAD

**Issue by peterblazejewicz** [marionettejs/marionettejs.com#254]
We need this to whitelist (a.k.a. approve) Twitter Card:
https://twittercommunity.com/t/warn-not-whitelisted-whitelisting-problem/32261
>Even when I do construct a URL for your image there is no image at:
http://marionettejs.com/images/marionette_logo.png

We will use full absolute path hardcoded.

**Comment by peterblazejewicz** [comment]
![20150216224916](https://cloud.githubusercontent.com/assets/14539/6219770/2efc7ac6-b62e-11e4-8512-548e167d1bad.jpg)
![20150216224822](https://cloud.githubusercontent.com/assets/14539/6219769/2eed49fc-b62e-11e4-94fc-2f2a47017ca8.jpg)

**Comment by samccone** [comment]
:clap: yesss

**Comment by peterblazejewicz** [comment]
Facebook cache is refreshed and it should go live in minutes:
![20150216232711](https://cloud.githubusercontent.com/assets/14539/6220184/761e16b2-b633-11e4-88e7-eb89b5271555.jpg)
