### ISSUE TITLE
Speed up initial page load.. youtube is SO SLOW

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#26]
when the page loads there is some serious lag because of youtube.. would love someone to look into how to fix this.

**Comment by paulfalgout** [comment]
So youtube might be fast enough if we just used `https://` in the URLs.  Also it looks like 2 of the vids have moved.

**Comment by jdaudier** [comment]
oops.... was trying to assign @kkemple but that didn't work

**Comment by samccone** [comment]
@kkemple literally destroyed this

![](https://31.media.tumblr.com/89ee74469c4d32a56a83108119fac659/tumblr_n9uo2p4XZM1sz7asho4_500.gif)
