### ISSUE TITLE
Marionette Logo favicon is missing on docs pages

### ISSUE THREAD

**Issue by kkemple** [marionettejs/marionettejs.com#268]
When you hit the Marionette www there is a nice logo favicon, when you navigate to the docs section of site you lose the favicon

**Comment by samccone** [comment]
:+1:

**Comment by samccone** [comment]
this should be a trivial fix to the layout file

**Comment by peterblazejewicz** [comment]
pending PR should also fix this:
![20150218222459](https://cloud.githubusercontent.com/assets/14539/6257016/15f072b8-b7bd-11e4-8182-51c4b35b77cc.jpg)

**Comment by peterblazejewicz** [comment]
Mind clearing your browser cache when testing this!

**Comment by kkemple** [comment]
:+1: @peterblazejewicz you have been killin it dude
