### ISSUE TITLE
Ditch scroll-to-top pattern from Marionette brand/logo

### ISSUE THREAD

**Issue by peterblazejewicz** [marionettejs/marionettejs.com#270]
This actually is an UX bug in situation when another pages are added that will be using common, shared components - like top, global navigation.
The users should be able to return to web site home in clear, quick way (it's internet DNA now). So let's ditch this scroll-to-top behavior attached to brand/logo.

Who's in favor?

:+1:

**Comment by jdaudier** [comment]
What about scroll to top for the homepage (since you're already at home) and go to homepage for the other ones?

**Comment by peterblazejewicz** [comment]
You can't have two different behaviours on your door lock key, correct? People will have to learn this and there is no real purpose I think - we could have an exception that on the first (home) page the logo is not clickable: http://www.nngroup.com/articles/113-design-guidelines-homepage-usability/ (see date)

**Comment by jdaudier** [comment]
@peterblazejewicz agreed now that I thought about it some more... since we have the scroll-to-top button already, we can just make the logo-text not clickable on the homepage

**Comment by jdaudier** [comment]
Now that we're making multiple pages... maybe we should convert to use Marionette :smile:

**Comment by peterblazejewicz** [comment]
@jdaudier progressively - yes, from static to dynamic (as Sam linked in other ticket)

**Comment by peterblazejewicz** [comment]
@jdaudier May I trash this behaviour? (the web-site with multiple pages is coming)

**Comment by jdaudier** [comment]
sure

**Comment by jdaudier** [comment]
by this you mean, clicking on logo text will take you to homepage and for the homepage, it's not clickable, right?

**Comment by peterblazejewicz** [comment]
Yes, the logo should always return people back to home page.

**Comment by peterblazejewicz** [comment]
The most recent doc:
https://developers.google.com/web/fundamentals/layouts/principles/easy-to-home?hl=en

**Comment by jdaudier** [comment]
:+1:
