### ISSUE TITLE
Video button regression

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#283]
![screen shot 2015-02-20 at 6 18 58 pm](https://cloud.githubusercontent.com/assets/883126/6311186/00425758-b92d-11e4-81bd-f8b035608b98.png)

**Comment by samccone** [comment]
duplicate #282

**Comment by jdaudier** [comment]
Was this not supposed to be see-through?  Forgot what it looked like before.

**Comment by samccone** [comment]
nope solid white

**Comment by samccone** [comment]
and red :)

**Comment by samccone** [comment]
like youtube

**Comment by peterblazejewicz** [comment]
That's build task target for production page - overoptimization is applied to this buttons. Let's check this:
https://github.com/marionettejs/marionettejs.com/pull/284#issuecomment-75361088

**Comment by peterblazejewicz** [comment]
If I copy/paste SVG from svg map dev build into DOM on web site everything turn white as expected. That' s definitely overoptimized svg:
![image](https://cloud.githubusercontent.com/assets/14539/6313940/ac8df7ae-b9c5-11e4-9a0f-93b875c4cb1c.png)
Now let's fix this

**Comment by peterblazejewicz** [comment]
There is a different SVG structure after compile-site phase:
http://jsbin.com/qokoma/2/edit

**Comment by peterblazejewicz** [comment]
Found it! Here:
https://github.com/addyosmani/critical/issues/63
WIP

**Comment by peterblazejewicz** [comment]
@samccone If we prepare custom `grunt-critical` installation that will use critical #master branch the problem will be fixed and can be later revisited when grunt-critical is updated. I can quickly verify fix via:
```
npm install git://github.com/addyosmani/critical#master
```
within grunt-critical module installation. It fetches `critical@0.5.4 node_modules/critical`

**Comment by jdaudier** [comment]
kudos on finding this... how did you narrow it down to critical?  google search?

**Comment by peterblazejewicz** [comment]
@jdaudier no, by elimination of tools that could alter inlined svgs. I've started with check if online/javascript/3rd party could alter this (e.g. 3rd party script loaded at runtime). After elimination I've checked build chain: `svgstore` first:
https://github.com/marionettejs/marionettejs.com/blob/master/gruntfile.js#L137-L144
then Jade engine including svgs:
https://github.com/marionettejs/marionettejs.com/blob/master/src/layouts/layout.jade#L61
and landed with the last tool used to somehow alter our markup on production:
https://github.com/marionettejs/marionettejs.com/blob/master/gruntfile.js#L314
'grunt-critical' uses couple of different tools (cheerio, penthouse, critical) - so checked issues on each.

**Comment by jdaudier** [comment]
gotcha...good job... i didn't get as far... only checked svgstore but noticed the svg sprite has the same code as the individual svg. 

I guess we'll have to do something similar to figure out https://github.com/marionettejs/marionettejs.com/issues/266

**Comment by peterblazejewicz** [comment]
@samccone what is the best way we could deal with this? Can we use forked grunt plugin with custom-dependency patch:
```diff
diff --git a/package.json b/package.json
index 3db5469..1ab1649 100644
--- a/package.json
+++ b/package.json
@@ -55,6 +55,6 @@
     "mkdirp": "0.5.0",
     "semver": "4.2.0",
     "underscore": "1.6.0",
-    "grunt-critical": "~0.1.1"
+    "grunt-critical": "git://github.com/peterblazejewicz/grunt-critical#patch/marionettejs.com"
   }
 }
```
https://github.com/peterblazejewicz/grunt-critical/commit/d1b5c35d3cd00494a2f72978db0450ab93cf496e
This seems to fix our problem - but `grunt-critical` tests fail with bumped `critical`. Can it be risky?

**Comment by samccone** [comment]
I would need to see the nature of the failure, but If this fixes our issue, it is fine to use the forked version. 
 :) 

I think the master version actually has my patch in it, so that we can generate multi resolution critical path css ;)

**Comment by jdaudier** [comment]
@samccone Can you explain in short what this mean?
>multi resolution critical path css

**Comment by samccone** [comment]
https://github.com/addyosmani/critical/pull/66

**Comment by peterblazejewicz** [comment]
@samccone 
here is output: https://gist.github.com/peterblazejewicz/9edb2c58bc8291a1e5c3
If I switch to master tests pass

**Comment by samccone** [comment]
yeah interesting, I am guessing one of the child dependencies changed, and thus their tests are invalid.

**Comment by peterblazejewicz** [comment]
We need to watch grunt-critical update and bump requirements in package.json after update:
https://github.com/addyosmani/critical/issues/63#issuecomment-76807066

**Comment by peterblazejewicz** [comment]
![20150305222715](https://cloud.githubusercontent.com/assets/14539/6514992/f156d106-c386-11e4-96f9-396246d477b8.jpg)
