### ISSUE TITLE
Fix issues with JavaScript on downloads pages

### ISSUE THREAD

**Issue by peterblazejewicz** [marionettejs/marionettejs.com#302]
![image](https://cloud.githubusercontent.com/assets/14539/6360753/c1979ea2-bc7c-11e4-96cb-fef54386dd6f.png)

**Comment by samccone** [comment]
oh no

**Comment by samccone** [comment]
I don't see those actually...

**Comment by peterblazejewicz** [comment]
hm, now it's fine. Which 3rd party code gets injected into page? (SPOF behaviour)

**Comment by peterblazejewicz** [comment]
Got this again. That's our code, there is no carousel on downloads page.
![20150224233549](https://cloud.githubusercontent.com/assets/14539/6360897/f1b789ca-bc7d-11e4-9fd1-a115fdf7c1d8.jpg)

I'll fix this with upcoming PR which adds blocks to layouts - so we will be able to include per-page scripts (but here we could add safe-check)

**Comment by samccone** [comment]
odd that mine did not blow up
