### ISSUE TITLE
Write story for Hotjar

### ISSUE THREAD

**Issue by jdaudier** [marionettejs/marionettejs.com#304]
Adding this here in case anyone wants to work on it...
Purpose: help promote Marionette & as a thank you for Hotjar for lifetime access

http://inside.hotjar.com/support/discussions/topics/1000051304

Ex: http://inside.hotjar.com/support/discussions/topics/1000053071

![2015-02-24_1636](https://cloud.githubusercontent.com/assets/1666031/6373365/3be51404-bcd8-11e4-885b-ea2df437b4a9.png)

**Comment by peterblazejewicz** [comment]
"Why we killed Twitter link and why it had it coming" (thx @plutokiller) is the good use case to use in this

**Comment by samccone** [comment]
I agree @peterblazejewicz :)

**Comment by jdaudier** [comment]
i even missed that... bye twitter bird

**Comment by samccone** [comment]
![](http://cache.desktopnexus.com/thumbnails/998492-bigthumbnail.jpg)

**Comment by jasonLaster** [comment]
Awe. Sad story

**Comment by jdaudier** [comment]
Closing 'cuz I don't think anyone has time for this :cry:
