### ISSUE TITLE
Design of docs needs a general cleanup pass

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#32]
pretty hard to read currently, just with the font size and elements... should be a simple iteration to make them much better :+1:

**Comment by samccone** [comment]
![](https://www.dropbox.com/s/vdq95jaci7bclg0/Screenshot%202015-01-02%2017.39.59.png?dl=0)

@lupinskij took an initial stab so far

**Comment by samccone** [comment]
![](https://photos-1.dropbox.com/t/2/AAA3CNOwyndta5TZICdNvhJHQnMRlZ3okw59uLhO3i3x8A/12/345341680/png/1024x768/2/_/0/4/Screenshot%202015-01-02%2017.39.59.png/CPD91aQBIAEoASgC/vdq95jaci7bclg0/AADG0aiNHfZbaXbW3TVe2Baza/Screenshot%202015-01-02%2017.39.59.png)

https://www.dropbox.com/s/vdq95jaci7bclg0/Screenshot%202015-01-02%2017.39.59.png?dl=0

**Comment by thejameskyle** [comment]
Oooh pretty, I kinda want the "Documentation Index" to exist in a different form, something like this sidebar: http://getbootstrap.com/components/. It should also be auto generated since it goes out of date easily.

**Comment by samccone** [comment]
yep, luckily the new deploy of the site is stupidly simple now (on purpose)
