### ISSUE TITLE
Unused font (blocking resource) on the Inspector page

### ISSUE THREAD

**Issue by peterblazejewicz** [marionettejs/marionettejs.com#327]
I think we have copied and pasted non used link to Questrial font:
https://github.com/marionettejs/marionettejs.com/blob/master/src/layouts/inspector-layout.jade#L13
I'm pretty sure it is not used on this specific page:
https://github.com/marionettejs/marionettejs.com/blob/master/src/stylesheets/inspector/index.scss#L8

x-ref: #326 (which should be merged first if LG)

**Comment by peterblazejewicz** [comment]
Firefox has built-in font listing feature:
![20150305194127](https://cloud.githubusercontent.com/assets/14539/6511865/eb929992-c36f-11e4-9c4d-5731f4604fba.jpg)

**Comment by samccone** [comment]
:clap:
