### ISSUE TITLE
Mobile menu toggle seems to no longer be working.

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#343]
On a phone if you click the menu button, it seems to no longer open :(

**Comment by peterblazejewicz** [comment]
menu depends on JS - scroll down and check if there are other possible problems, is there background of video missing? If we get server or 3rd party loading problems on mobile our code (which loads at the end) will suffer most).
btw, see response time for fonts and Transifex here:
http://www.webpagetest.org/result/150307_FR_REY/

**Comment by jdaudier** [comment]
the hamburger icon works for me but I'm on Android - Samsung Galaxy S4

**Comment by samccone** [comment]
ok I was on a really poor network, and this is a great find actually, I am going to inline the script because, we should not prevent this from working due to network critical load time. :+1:
