### ISSUE TITLE
Add missing hotjar code on the inspector page

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#368]

**Comment by peterblazejewicz** [comment]
I've changed URL to end with slash and make sure that data is sent to Hotjar:
![20150312214232](https://cloud.githubusercontent.com/assets/14539/6627756/cd11ca6a-c900-11e4-8ab3-2b0dece40f35.jpg)
(that's me on counter)
![20150312214522](https://cloud.githubusercontent.com/assets/14539/6627817/2b30f0da-c901-11e4-9723-4d45750ecb4d.jpg)
So closed - missing trailing slash was the culprit

**Comment by peterblazejewicz** [comment]
http://inside.hotjar.com/support/solutions/articles/1000166814-why-is-my-heatmap-not-tracking-visitors-
