### ISSUE TITLE
Need to add a polyfill for RAF

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#387]

**Comment by samccone** [comment]
this computer is far too old to upload images, but it is a real issue, trust me :)

**Comment by samccone** [comment]
this computer is far too old to upload images, but it is a real issue, trust me :)

**Comment by jdaudier** [comment]
@samccone what feature is this that's using RAF? Logo animation?

**Comment by samccone** [comment]
request animation frame :)

**Comment by jdaudier** [comment]
ok i know that... but let me ask it a different way, what's broken?

**Comment by paulfalgout** [comment]
I can find RAF in use.. closing for now
