### ISSUE TITLE
Set up initial structure for Guides

### ISSUE THREAD

**Issue by jdaudier** [marionettejs/marionettejs.com#389]
Steps:
1. Create a "guides" folder in src repo
2. Create custom grunt task (fun!)
3. Update gruntfile in www to pull it in 
4. Create a index hbs template
5. Create a template hbs template
6. Test out setup using @benmccormick sample text: https://gist.github.com/benmccormick/7fb48e9c411db00c0094
7. Sleep :sleeping:

*Did I miss anything people?*

**Comment by peterblazejewicz** [comment]
5a separate `.scss` either top level if `guides` are top level without master template or as page style sheet.

**Comment by jdaudier** [comment]
@peterblazejewicz For the sake of time, I just set up a [Gitbook](https://www.gitbook.com/book/marionette/marionette-guides)

We can always convert the content over later on but Gitbook will give us PDF, ePub, mobi, and a site right out of the box which is kinda nice.
