### ISSUE TITLE
Marionette Team Page

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/marionettejs.com#406]
We're a modest bunch, but that doesn't mean there shouldn't be a team page

https://github.com/marionettejs

I think it'd do a good job of promoting legitimacy for the org and get some marketing for the companies we work for and their contributions in terms of time

**Comment by peterblazejewicz** [comment]
@jdaudier we will need a better grid

**Comment by jasonLaster** [comment]
lol

**Comment by samccone** [comment]
heh :)

**Comment by jdaudier** [comment]
@trezy Thanks!  I just noticed this today. Looks awesome!

**Comment by trezy** [comment]
;-)
