### ISSUE TITLE
License?  Reuse?

### ISSUE THREAD

**Issue by geekdave** [marionettejs/marionettejs.com#417]
My team is releasing a new OSS project, and we've been looking for a project website with similar requirements to borrow/steal from :)

We love the look of the Marionette site, how it organizes tons of information and docs in a clean and uncluttered way, and how it generates the docs based on the parent project.

The only reference I saw to a license was in the `package.json`, which references an ISC license: https://github.com/marionettejs/marionettejs.com/blob/master/package.json#L21

I was wondering if this is accurate, and if you'd be open to another OSS project borrowing the templates/build for this site.  If so, how would you want the attribution to work?

Thanks!

**Comment by samccone** [comment]
oh yeah this is totally MIT, let me update that

**Comment by samccone** [comment]
done and done :white_check_mark:

**Comment by geekdave** [comment]
Awesome!  Thanks @samccone !
