### ISSUE TITLE
Embed Gitter chat room

### ISSUE THREAD

**Issue by jdaudier** [marionettejs/marionettejs.com#427]
A JavaScript snippet can be pasted into the site and will add a button and chat elements into the page. We can also customize the behaviur by utilizing the JavaScript API.

Visit https://sidecar.gitter.im to see it in action, copy the snippet and checkout the API documentation.

https://gitter.im/gitterHQ/sidecar

/cc @trezy

**Comment by denar90** [comment]
Merged #482
