### ISSUE TITLE
Implement Marionette

### ISSUE THREAD

**Issue by trezy** [marionettejs/marionettejs.com#429]
We're loading Marionette into the website. It would seem that it's not actually used anywhere, it's only there to allow hackers to use it in the console.

With my recent team page I could see a value in using Marionette views. @paulfalgout mentioned that the example section could benefit from being written in Marionette. #427 could also benefit from having Marionette. It's not that none of these things could be done without Marionette but I think it would be good to dogfood our product.

I'm on the fence about whether this is necessary or not so I suppose I'm looking for a conversation which could push one way or the other.

**Comment by peterblazejewicz** [comment]
> It would seem that it's not actually used anywhere, it's only there to allow hackers to use it in the console.

Yes, that's correct. There was (and still is) a positive thing to have a framework site built as static, non-moving resources (the web working as search engine). 
If you go with dynamic content, I'd help to instruct it for JSON-DL or whatever helps to crawl/index content.

**Comment by samccone** [comment]
so, I want to keep it on the page, because it is nice to just put code into the console when messing around, I am fine keeping the site almost entirely static.. but it might be nice to have a touch of Mn in use :)

**Comment by denar90** [comment]
agree with @samccone, it's really useful to play with Mn in console on site. Closing then.
