### ISSUE TITLE
marionettejs.com is down

### ISSUE THREAD

**Issue by codekiln** [marionettejs/marionettejs.com#430]
http://marionettejs.com/ is currently down

```
The page you are looking for cannot be found.

Similar results are provided below, or you can try another search


Search site
To find the missing content, try these steps:

Visit the domain home page
Reload this page
Search for the missing content with the search box above
Loading...

SmartErrors powered by CloudFlarePrivacy policy
```

**Comment by trezy** [comment]
Running the deploy script seems to have us back up. I'll leave this issue open and monitor the page for the rest of the day just in case.

**Comment by trezy** [comment]
I've been monitoring the site and it hasn't gone down again all day. I'm pretty confident this was a fluke, likely just some sort of compile issue. I'm closing the issue but feel free to repoen if this occurs again.

**Comment by samccone** [comment]
the deploy however did not really work, looks like we are now missing $ on the page

**Comment by trezy** [comment]
Way to rain on my parade, @samccone. I'm looking into it meow.

**Comment by trezy** [comment]
Fixed again. As I said in Gitter, I'm chalking this up to my switching node versions so frequently.
