### ISSUE TITLE
Yellow text on white background is very difficult to read (http://marionettejs.com/updates/)

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/marionettejs.com#441]
From @tjoneseng from https://github.com/marionettejs/backbone.marionette/issues/2945

The changelog styling uses yellow on white for some links.  Those are basically impossible to read.

![image](https://cloud.githubusercontent.com/assets/13930/13861206/4401f1ce-ec49-11e5-85ed-6cd962a0a8c6.png)

**Comment by samccone** [comment]
oh no!
