### ISSUE TITLE
Optimize anti-FOUC/critical on the home page

### ISSUE THREAD

**Issue by peterblazejewicz** [marionettejs/marionettejs.com#444]
I think that after search and updates features have been added the the critical path (css) implementation should be tested and refactored.
These are single screenshots from the home page (the changes are very quick, and you could not notice them if you are on DSL connection):
![image](https://cloud.githubusercontent.com/assets/14539/13899653/f8a7c5c6-edf3-11e5-86c4-b1012fe29de5.png)
![image](https://cloud.githubusercontent.com/assets/14539/13899656/060eb7f6-edf4-11e5-91eb-de6f7bb38c20.png)
![image](https://cloud.githubusercontent.com/assets/14539/13899663/181a76a6-edf4-11e5-9ab2-a2d34d1c2270.png)
The users on slow (think GRPS or clogged 3G+)
Let me know if you've experienced this.
@jdaudier  @samccone

**Comment by MeoMix** [comment]
Yeah I've seen this as well.

**Comment by samccone** [comment]
yeah this needs a MAJOR fixup

**Comment by jdaudier** [comment]
I have.  Is this due to critical CSS?
