### ISSUE TITLE
Add order for doc files

### ISSUE THREAD

**Issue by denar90** [marionettejs/marionettejs.com#447]
I propose to add order for doc files. Now we have it alphabetically in nav bar
```javascript
<nav>
          <% files.forEach(function(file) { %>
            <a href="/docs/<%- tag + '/' + file.basename %>.html"><%- file.title %></a>
          <% }); %>
</nav>
```

Purpose e.g. `installation.doc` which has to be first and after all other stuff. Issue related to https://github.com/marionettejs/backbone.marionette/issues/2963

I propose a few ways how it can be solved. 

 - add list of doc files in some config and render it
 - mark needed doc file names with order number also in some static config object.

What do you think guys?

**Comment by samccone** [comment]
:+1:

**Comment by peterblazejewicz** [comment]
@denar90 
maybe only a *topics* object needs to be added, e.g.:
```
<nav>
    <% topics.forEach(function(file) { %>
      <a href="/docs/<%- tag + '/' + file.basename %>.html"><%- file.title %></a>
    <% }); %>
    <hr />
    <% files.forEach(function(file) { %>
      <a href="/docs/<%- tag + '/' + file.basename %>.html"><%- file.title %></a>
    <% }); %>
    <hr />
    <% topics.forEach(function(file) { %>
      <a href="/docs/<%- tag + '/' + file.basename %>.html"><%- file.title %></a>
    <% }); %>
  </nav>
```
where `topics` is just a set of most important `files` and `files`:
```
files: _.difference(files, topics)
```
The topics object can be created in the same place where files are parsed.

**Comment by denar90** [comment]
It make sense. Do we need additional line of topics at the bottom?

**Comment by denar90** [comment]
I've created PR. It's my vision of solving issue. Can someone take a look? Maybe I'm wrong.
