### ISSUE TITLE
Ignore pre release tags for docs 

### ISSUE THREAD

**Issue by denar90** [marionettejs/marionettejs.com#449]
Now we have a problem with doc page where on `current` [page](http://marionettejs.com/docs/current/), version which we have is `v3.0.0-pre.2` this is not good, because v3.pre.. docs are not ready and people are really confused. I propose to ignore in doc page any pre tags at all.
I'll prepare PR asap.

**Comment by scott-w** [comment]
Is this related to marionettejs/backbone.marionette#3002?

**Comment by denar90** [comment]
Yes. Forgot to add link on that.

**Comment by denar90** [comment]
@scott-w should I leave this PR for @curzonj ?

**Comment by denar90** [comment]
Created PR.

**Comment by denar90** [comment]
Sorry guys, maybe I'm to rush or something but I realized that I saw this problem (told other colleagues that here some problem, be sure that you are using right version) but didn't do nothing for fixing this...
