### ISSUE TITLE
Update site after Mn release 

### ISSUE THREAD

**Issue by denar90** [marionettejs/marionettejs.com#456]
We need to update site automatically when Mn release a new version.
I think something like `travis-runner.sh` has to be added to framework repo.

**Comment by ahumphreys87** [comment]
Good idea.

However I believe the travis deploy of the site is broken at the moment. Be
good to get that fixed

**Comment by denar90** [comment]
It looks fine right now 
https://travis-ci.org/marionettejs/marionettejs.com

**Comment by denar90** [comment]
Closing this due to merged PR in main Mn repo.
