### ISSUE TITLE
"The page you are looking for cannot be found."

### ISSUE THREAD

**Issue by charlex** [marionettejs/marionettejs.com#460]
Looks like cloudflare is having some trouble today
<img width="710" alt="screen shot 2016-05-29 at 2 14 40 pm" src="https://cloud.githubusercontent.com/assets/1542740/15636053/cb59f396-25a7-11e6-80cc-1554fd79d41f.png">

**Comment by paulfalgout** [comment]
version `2.5.6` was a mistake release to the website.  This version never really existed and was pulled.
