### ISSUE TITLE
Documentation Renderer inserts <br>

### ISSUE THREAD

**Issue by scott-w** [marionettejs/marionettejs.com#462]
In the docs, I tend to enforce an 80-line width in the source. The task that converts the MD docs into HTML seems to be preserving the newlines as `<br>` tags.

I do think it'll make sense to have a width enforced for readability but I'd rather see that enforced in CSS than allowing the source to affect it.

**Comment by paulfalgout** [comment]
I think this is a dupe of https://github.com/marionettejs/marionettejs.com/pull/388 / https://github.com/marionettejs/marionettejs.com/issues/384

**Comment by scott-w** [comment]
Good shout, thanks for spotting this. Closing as duplicate of #384
