### ISSUE TITLE
New site version

### ISSUE THREAD

**Issue by denar90** [marionettejs/marionettejs.com#467]
What about to upgrade site a bit. 
- upgrade design (use material design, whatever ...)
- replace `grunt` by something else (gulp, whatever ...)
- improve compilers (add tests etс)
- more stuff ...

Any thoughts? Is it worth it?

**Comment by jdaudier** [comment]
I'm ok to anything to bring values to the community.

**Comment by peterblazejewicz** [comment]
@denar90 
You can use MDL, there are no components on web site that would require anything non available in https://getmdl.io/components/index.html
I'm accustomed with MDL if you prefer that lib

**Comment by denar90** [comment]
Tried to play with it a bit. Think it's not worth it...
