### ISSUE TITLE
Search menu is transparent

### ISSUE THREAD

**Issue by jdaudier** [marionettejs/marionettejs.com#496]
![image](https://cloud.githubusercontent.com/assets/1666031/24464885/57b13a3c-1479-11e7-9958-70a3ddc5d553.png)

**Comment by peterblazejewicz** [comment]
list of classes:
```css
.aa-dropdown-menu {
}
.aa-suggestion {
}
.aa-suggestion:hover, 
.aa-suggestion.aa-cursor {
}
.aa-suggestion > span:first-child {
}
.aa-suggestion > span:last-child {
}
.aa-suggestion > span:first-child em, 
.aa-suggestion > span:last-child em {
}
```
Example markup:
https://gist.github.com/peterblazejewicz/773da5a0794c047ae3672d5495637e43
https://www.algolia.com/doc/guides/search/auto-complete/
