### ISSUE TITLE
Think about what is in our header

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#52]
![](http://dl.dropbox.com/u/36928599/Screenshots/0ob.png)
![](http://dl.dropbox.com/u/36928599/Screenshots/0oc.png)
![](http://dl.dropbox.com/u/36928599/Screenshots/0od.png)
![](http://dl.dropbox.com/u/36928599/Screenshots/0of.png)

and then us..

![](http://dl.dropbox.com/u/36928599/Screenshots/0oe.png)

I think we are wasting way too much space on a logo and there is no clear CTA

**Comment by jdaudier** [comment]
maybe removing the gray bar will help before we switch to fixed top nav

**Comment by jdaudier** [comment]
or we can make the header thinner, move logo smaller to the left, add the tagline and download button inside the thinner header

**Comment by jdaudier** [comment]
one idea...
![new nav](https://cloud.githubusercontent.com/assets/1666031/5600874/3b44ba80-92b3-11e4-8b68-2bf553c898f0.png)

**Comment by jdaudier** [comment]
another idea...
![nav2](https://cloud.githubusercontent.com/assets/1666031/5600935/c90ba3a0-92b4-11e4-9a2c-5669c56032db.png)

**Comment by jdaudier** [comment]
or... i think i like white behind our logo
![nav3](https://cloud.githubusercontent.com/assets/1666031/5600998/22148dca-92b7-11e4-9af4-1201d9a01515.png)

**Comment by jdaudier** [comment]
fav version so far inspired by npm
![v4](https://cloud.githubusercontent.com/assets/1666031/5601030/67d4eb42-92b8-11e4-9ef2-7159f004a448.png)

**Comment by samccone** [comment]
from @lupinskij 

![](http://dl.dropbox.com/u/36928599/Screenshots/0oh.png)

**Comment by samccone** [comment]
I just want to add a link to the docs and then this can be closed :book:

**Comment by jmeas** [comment]
@lupinskij's 2nd mockup is :+1:

**Comment by jasonLaster** [comment]
Yup - :point_up_2: **2**

**Comment by thejameskyle** [comment]
What is the text in #2 even going to say?

**Comment by jdaudier** [comment]
it can say something similar to what's on http://dev.marionettejs.com unless someone has a better / simpler description

**Comment by trezy** [comment]
I'm totally on board. @samccone, that's a great point that there's no CTA. I'm on board for #2.

**Comment by jasonLaster** [comment]
who wrote this beautiful text?

```
Marionette simplifies your Backbone application code with robust views and architecture solutions.
```

**Comment by jdaudier** [comment]
Thanks @jasonLaster!  Guess my marketing background is coming in handy.

**Comment by samccone** [comment]
![](http://i.minus.com/ib0hDuxpPrebyd.gif?q=0.856984931219)

**Comment by samccone** [comment]
![ib0hduxpprebyd](https://cloud.githubusercontent.com/assets/883126/5616642/9346eeb0-94d4-11e4-81c6-a83677692cb7.gif)

**Comment by kkemple** [comment]
![dumbledore-applause](https://cloud.githubusercontent.com/assets/3629876/5616663/e174f2b2-94d4-11e4-8bfd-ae7bd6fc12b5.gif)

**Comment by jasonLaster** [comment]
Yea. Only critique would be. It doesn't convey, my framework is betta than yo fm.

**Comment by kkemple** [comment]
:arrow_up: :+1:
