### ISSUE TITLE
Marionette logo needs to be animated... 

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#54]
leaving this one wide open.......

**Comment by thejameskyle** [comment]
Are you sure you want to leave this one open ended with me around?

**Comment by samccone** [comment]
yes

**Comment by thejameskyle** [comment]
_clicks photoshop_

**Comment by thejameskyle** [comment]
<img src="https://cloud.githubusercontent.com/assets/952783/5601048/cb702ba8-929f-11e4-9f62-f1c71d302ae6.gif" width="800">

**Comment by jmeas** [comment]
ROFL @thejameskyle

**Comment by jmeas** [comment]
It would be very easy for an animated logo to look like a cheesy & superfluous embellishment, I think. If we do this, we should make sure it doesn't look goofy.

I don't think it's a bad idea to just leave it static.

**Comment by jasonLaster** [comment]
I think @thejameskyle - just made our first easteregg.

now how do you trigger it... if only we had a virtual-doooo

**Comment by JSteunou** [comment]
Konami code of course https://github.com/snaptortoise/konami-js ;)

**Comment by trezy** [comment]
Haha, I'll throw something into the refactor branch. I had an idea for it already. Like @jmeas said, it's easy for something like that to be cheesy. It needs to be more of an easter egg than anything. I'm thinking an SVG version of the logo with a tiny animation where the handle moves and the legs wiggle a little.

**Comment by samccone** [comment]
Yeppp

**Comment by kkemple** [comment]
Another konami function :: https://github.com/kkemple/konami

**Comment by kkemple** [comment]
Thought it would be fun to make a Konami behavior :: https://gist.github.com/kkemple/8bdc20cae7cdda6b7e53

**Comment by thejameskyle** [comment]
> Thought it would be fun to make a Konami behavior

Oh god, so good.

**Comment by samccone** [comment]
:)

**Comment by JSteunou** [comment]
That's why wee need a Marionette repository. Collecting all those nice behaviors :p

**Comment by paulfalgout** [comment]
I can't believe I'm taking part in this.  1st rough draft of an svg animation... obviously something we'd want behind a rollover or something..  

Someone. stop. me.  

Alternatively.. worth continuing?   Or someone take over:  http://editor.animatron.com/#p=5701b35445cdc73a19ea98f4&c=2be7f767dfde1a78a4fac102


<img src="http://otterball.com/marionette-anim.svg"  width="177px" >

**Comment by thejameskyle** [comment]
It looks like it's walking towards me...

**Comment by paulfalgout** [comment]
Well it's just a puppet.. it's an illusion.

**Comment by thejameskyle** [comment]
No, you're an illusion.

**Comment by paulfalgout** [comment]
:ghost:

**Comment by trezy** [comment]
@paulfalgout I love it! The only thing that bothers me is that the handles are moving wrong. When the handle goes down, the leg should go down, too.

**Comment by samccone** [comment]
ha more than happy with this for a first pass

**Comment by jdaudier** [comment]
How about something subtle like this - only when you mouse enter...

**Video of the animation:**
http://screencast.com/t/XKIns9rbZ6

**Animated gif (not as smooth as the video but you get the idea:**
![q6ijyacgjq](https://cloud.githubusercontent.com/assets/1666031/5791019/d5a3d288-9e83-11e4-88cd-714282703ec8.gif)

**Comment by samccone** [comment]
Yes please

**Comment by jdaudier** [comment]
ok @samccone just PR'ed
