### ISSUE TITLE
Website Does not Load (Domain Expired)

### ISSUE THREAD

**Issue by crantila** [marionettejs/marionettejs.com#545]
Hello. At the beginning of September 2023, the MarionetteJS domain name expired, leaving the website inaccessible. We still use MarionetteJS where I work, with no plans to migrate to another framework. Therefore, we still need to view the documentation from time to time. In case there are other people in the same situation, I'm sharing two things we did to help:

1. There's a copy of the "gh-pages" branch of this repository (with some changes) available at my [marionette_website repository](https://github.com/crantila/marionette_website), which you can clone and view on your own computer.
2. Those files have been posted to https://marionettejs.netlify.app so you can view them online too.

Thank you to all the MarionetteJS contributors for providing a solid set of libraries. BackboneJS-based solutions aren't very popular in 2023, but Marionette still works well for us, and that's a credit to the endless hours of hard work from the development community.

**Comment by paulfalgout** [comment]
Assuming I can get @jamiebuilds to transfer or reinstate marionettejs.com I'll probably end up redirecting it, but I've moved the site to http://marionette.js.org/

**Comment by samccone** [comment]
https://marionettejs.com/ looks to be working again !
