### ISSUE TITLE
concat minify and uglify all js and css

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#57]

**Comment by kkemple** [comment]
@samccone i can do this one tonight if you want

**Comment by samccone** [comment]
awwwww yes

**Comment by thejameskyle** [comment]
You know CloudFlare can do this for you automatically right?

**Comment by samccone** [comment]
hot dang

**Comment by paulfalgout** [comment]
:+1: for cloudflare doing it

**Comment by samccone** [comment]
@thejameskyle does cloudflare have multi login yet? 

I am unable to evaluate this as being a good solution until I am able to look closer at it (in the ui), however concating and minifiying scripts is a pretty solved problem on grunt, so based on what I currently know I think a first pass having grunt do it, and then in a second pass delegating to cloudflare seems like a valid approach

**Comment by thejameskyle** [comment]
@samccone Nope nothing has changed in the last 3 days since you asked. :stuck_out_tongue_winking_eye:

**Comment by jasonLaster** [comment]
come on @thejameskyle - get it together.

**Comment by samccone** [comment]
hahahahaha :P
