### ISSUE TITLE
compress and attack all slow network assets

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#59]
![](http://dl.dropbox.com/u/36928599/Screenshots/0oi.png)

**Comment by samccone** [comment]
I prob seem crazy, but... I think we can get this page to load so fast .. there still is some delay.
I think we can grab all external images and put them in the repo.. after compressing the heck out of them
this stacks on top of this issue

https://github.com/marionettejs/marionettejs.com/issues/57

**Comment by samccone** [comment]
#85

**Comment by paulfalgout** [comment]
Next steps here.
- [ ] Host and compress those youtube preview images locally
- [ ] Replace the 2 gif logos with png versions (for consistency and so google doesn't complain
- [ ] Investigate why google wants the mojotech logo resized

**Comment by jdaudier** [comment]
site is so fast now! :+1:
