### ISSUE TITLE
Mobile nav

### ISSUE THREAD

**Issue by sethkrasnianski** [marionettejs/marionettejs.com#71]
Around iPhone 5 portrait:
![screen shot 2015-01-04 at 11 27 55 pm](https://cloud.githubusercontent.com/assets/1910114/5609231/5b54b21e-9469-11e4-81f1-27c605297043.png)

Should probably do a hamburger and toggle the `ul` with the `li`s style set to `display: block` etc...
This could apply to all hand held (non-tablet) devices.

**Comment by jasonLaster** [comment]
Yup. I'd say "block" so the links are tappable.

**Comment by trezy** [comment]
This should be fixed in the CSS refactor branch once I add the responsive stuff back in. However, I'd vote for a hamburger icon. @jdaudier even mentioned using an actual hamburger rather than the standard icon. I thought it was clever. ;-)

**Comment by kkemple** [comment]
would it not hurt to have an off-canvas menu, the docs could benefit from that as well :smile:

**Comment by kkemple** [comment]
on mobile*

**Comment by trezy** [comment]
I recently built a native app style off screen menu we could utilize for mobile if we wanted to be all snazzy and such:
http://codepen.io/trezy/pen/KwzXWK

**Comment by samccone** [comment]
of course we do

**Comment by sethkrasnianski** [comment]
:+1: for actual white hamburger silhouette

**Comment by samccone** [comment]
:+1: for someone to bring me an actual hamburger

**Comment by kkemple** [comment]
mmmmm :hamburger:

**Comment by jdaudier** [comment]
Here's a vid: http://screencast.com/t/8F4yMysO6

![nav](https://cloud.githubusercontent.com/assets/1666031/5660004/c196c2ac-96e8-11e4-9803-84a25e14f1a5.png)

----
**ON CLICK** 

![nav2](https://cloud.githubusercontent.com/assets/1666031/5660006/c5abb6ae-96e8-11e4-8d02-777243a7e2bd.png)

**Comment by samccone** [comment]
;)

**Comment by kkemple** [comment]
can the hamburger have a bit more breathing room (padding) around the top and bottom

**Comment by jdaudier** [comment]
Sure @kkemple we all need some personal space when eating a hamburger
