### ISSUE TITLE
Headlines # href in doc headlines dont match up with github.

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#72]
For instance 

http://dev.marionettejs.com/docs/v2.3.0/marionette.behavior.html

`http://dev.marionettejs.com/docs/v2.3.0/marionette.behavior.html#$el-and-el`

You can use the table of contents as a guide as to how the links should be serialized. But i think this is a difference in githubs marked version and what we are using.

**Comment by paulfalgout** [comment]
I'll get this, this afternoon.. know exactly how to fix it.

**Comment by samccone** [comment]
wooo

**Comment by jasonLaster** [comment]
Thanks Paul!
