### ISSUE TITLE
is the center of the area "above the fold" getting too cluttered?

### ISSUE THREAD

**Issue by kkemple** [marionettejs/marionettejs.com#79]
It is looking kind of crowded in the middle of the screen when you land on the page, i included a suggested adjustment

How it is currently:
![clutter](https://cloud.githubusercontent.com/assets/3629876/5624449/7103f1cc-9533-11e4-90d8-8f5fd180f57b.jpg)

What I propose:
![proposed](https://cloud.githubusercontent.com/assets/3629876/5624448/7101df86-9533-11e4-8e70-a7742d747612.jpg)

**Comment by jdaudier** [comment]
OOPS!  Just saw this... let me know if I should close my PR

![new](https://cloud.githubusercontent.com/assets/1666031/5625825/3d1e6a3c-9550-11e4-9061-84c45380e370.png)

inspired by...
![foundation](https://cloud.githubusercontent.com/assets/1666031/5625831/4b2bd272-9550-11e4-8e24-fd78f744465e.png)

**Comment by jdaudier** [comment]
another option

![new2](https://cloud.githubusercontent.com/assets/1666031/5626016/6473101c-9553-11e4-9061-fb6b79384ae0.png)

**Comment by jdaudier** [comment]
another option

![new2](https://cloud.githubusercontent.com/assets/1666031/5626083/501f355e-9554-11e4-8557-b6db3a9f2b6d.png)

**Comment by jdaudier** [comment]
OOPS! Sorry guys... I read this after I already started making some changes.  LMK what you think. Close my PR  https://github.com/marionettejs/marionettejs.com/pull/84 if you don't like it.

![new](https://cloud.githubusercontent.com/assets/1666031/5627184/01fc170c-9563-11e4-973e-d4641416909a.png)

![new2](https://cloud.githubusercontent.com/assets/1666031/5627187/0760dd5e-9563-11e4-9c33-7a8397459908.png)

**Comment by paulfalgout** [comment]
@jdaudier interesting.  I like getting rid of the gitter badge.  Looks fine on github, but moderately out of place on the site.  It's also intriguing that we have a support link that goes directly to gitter.  makes sense.

**Comment by kkemple** [comment]
i love the support link and removing the gitter badge! also since we have twitter in header and github star button by contribute I think we should remove the social section from the top of the page, see following:

![marionette_js_ _the_backbone_framework](https://cloud.githubusercontent.com/assets/3629876/5628576/4df92974-9577-11e4-905d-e562a56d88fd.jpg)

**Comment by jdaudier** [comment]
just to clarify, so you mean remove the twitter logo from the top red nav?

**Comment by kkemple** [comment]
sorry no, i meant to remove the social section right below the billboard section, but looks like you have done so already lol

**Comment by jdaudier** [comment]
yup thanks!

**Comment by kkemple** [comment]
looks amazing by the way :+1:

**Comment by kkemple** [comment]
@jdaudier @samccone it's safe to say this issue can be closed because @jdaudier fixes this issue in #84
