### ISSUE TITLE
Fix header area to not break until a much smaller width

### ISSUE THREAD

**Issue by samccone** [marionettejs/marionettejs.com#88]
Currently this happens..

![screen shot 2015-01-06 at 9 44 23 am](https://cloud.githubusercontent.com/assets/883126/5630109/ab7e4fa0-9588-11e4-9c8d-9af7556b6e79.png)

because we are hard coding pxl values inside a % container.. should be a simple fix.. @trezy does your branch address this?

**Comment by trezy** [comment]
Yup, it will. I'm using `em`s, `rem`s, and flexbox for everything.

**Comment by samccone** [comment]
cool no pressure but any eta on even a subset pr?

**Comment by kkemple** [comment]
@trezy you are the man...I was going to work on responsive stuff...guess I
will find some docs work :smile:

**Comment by samccone** [comment]
heh @kkemple 

there will be a fun bit of work we are going to have to do with @chetharrison's stuff.. it is really a game changer for docs but we are going to have to both more doc content and do a bit of style work.. that said tho.. it is so so amazing

**Comment by kkemple** [comment]
I'm ready to see the updates! Any eta on them?

**Comment by trezy** [comment]
Sorry about the delays. I'm going to try to get the whole thing done and pushed early next week at the latest. I'd do it sooner but I've got a million things going on starting tomorrow. I'll try to get it all done tonight if I have time.

However, feel free to pull down my branch and do some work there.

**Comment by samccone** [comment]
wooohooo

**Comment by kkemple** [comment]
@trezy I will take a look and see if I can help you out tonight

**Comment by trezy** [comment]
Awesome, I appreciate it! The main things left on the refactor are bringing back in the new styles and rebasing. Then it's done!
